name: CI/CD Music Bot

on:
  push:
    branches:
      - main
    paths:
      - 'cmd/bot/**'
      - 'internal/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./cmd/bot/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/music-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/music-bot:latest
            docker stop music-bot-container || true
            docker rm music-bot-container || true
            docker run -d \
              --name music-bot-container \
              --network music_network \
              -p 127.0.0.1:8080:8080 \
              -e BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
              -e PORT="8080" \
              -e DB_HOST="music_bot_db" \
              -e DB_USER="music_user" \
              -e DB_NAME="music_db" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/music-bot:latest
